import Head from 'next/head'

const AboutPage = (props) => {
  return(
    <>
      <Head>
        <title>My Site -  About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>about page</h1>
      </div>
    </>
  )
}

export default AboutPage
