import { useEffect } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'//

import List from '@/components/List'
// import { getProducts } from '@lib/firebase'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  useEffect(() => {
    if (window !== undefined) {
      // getProducts()
    }

  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Products</h1>
        <div>
          <List />
        </div>
      </main>
    </>
  )
}
